"""Ablation-first recursive language-model substrate."""

from .accounting import (
    CompositionReceipt,
    ParameterAccounting,
    TokenizerScaleAccounting,
    TokenizerScreenAccounting,
    TokenizerTargetDecisionContract,
    composition_receipt,
    estimate_dense_unique_parameters,
    lexical_parameter_share,
    parameter_accounting,
    tokenizer_screen_accounting,
)
from .bicameral import SwapLinear
from .callosum import (
    CALLOSUM_RETENTION_TRIPWIRE,
    EmpiricalCarrierRetentionReceipt,
    HemisphereGradientCosineReceipt,
    PerBandBirkhoffCallosum,
    empirical_disagreement_retention_receipt,
    hemisphere_gradient_cosine_receipt,
)
from .config import (
    RATIFIED_TARGET_AUTHORITY,
    RATIFIED_TARGET_AUTHORITY_SHA256,
    RATIFIED_TARGET_D_MODEL,
    RATIFIED_TARGET_ROUNDED_UNIQUE_PARAMETERS_BY_CORE,
    RATIFIED_TARGET_REFERENCE_VOCAB_SIZE,
    REGISTERED_CORE_BLOCK_COUNTS,
    REGISTERED_PROXY_BLOCK_SPLITS,
    REGISTERED_TARGET_BLOCK_SPLITS,
    TOKENIZER_VOCAB_CANDIDATES,
    AblationLMConfig,
    registered_mu_r_configs,
    registered_proxy_reallocation_configs,
    registered_target_configs,
)
from .diagnostics import (
    RouterCalibrationDecision,
    RouterMomentSnapshot,
    router_calibration_stability,
)
from .geometry import Cl20Rotor, LaneModeState, cl20_rotate, lanes_to_modes
from .hadamard import orthonormal_wht, sequency_permutation, wht
from .model import AblationLM, AblationLMOutput
from .observatory import ObservatoryBlocked, ObservatoryGuard, T14bReceipt

__all__ = [
    "AblationLM",
    "AblationLMConfig",
    "AblationLMOutput",
    "CALLOSUM_RETENTION_TRIPWIRE",
    "Cl20Rotor",
    "CompositionReceipt",
    "EmpiricalCarrierRetentionReceipt",
    "HemisphereGradientCosineReceipt",
    "LaneModeState",
    "ObservatoryBlocked",
    "ObservatoryGuard",
    "ParameterAccounting",
    "PerBandBirkhoffCallosum",
    "RATIFIED_TARGET_AUTHORITY",
    "RATIFIED_TARGET_AUTHORITY_SHA256",
    "RATIFIED_TARGET_D_MODEL",
    "RATIFIED_TARGET_ROUNDED_UNIQUE_PARAMETERS_BY_CORE",
    "RATIFIED_TARGET_REFERENCE_VOCAB_SIZE",
    "RouterCalibrationDecision",
    "RouterMomentSnapshot",
    "REGISTERED_CORE_BLOCK_COUNTS",
    "REGISTERED_PROXY_BLOCK_SPLITS",
    "REGISTERED_TARGET_BLOCK_SPLITS",
    "TOKENIZER_VOCAB_CANDIDATES",
    "SwapLinear",
    "T14bReceipt",
    "TokenizerScaleAccounting",
    "TokenizerScreenAccounting",
    "TokenizerTargetDecisionContract",
    "composition_receipt",
    "estimate_dense_unique_parameters",
    "lexical_parameter_share",
    "orthonormal_wht",
    "cl20_rotate",
    "lanes_to_modes",
    "parameter_accounting",
    "empirical_disagreement_retention_receipt",
    "hemisphere_gradient_cosine_receipt",
    "registered_mu_r_configs",
    "registered_proxy_reallocation_configs",
    "registered_target_configs",
    "router_calibration_stability",
    "sequency_permutation",
    "tokenizer_screen_accounting",
    "wht",
]
