"""Ablation-first recursive language-model substrate."""

from .accounting import (
    CompositionReceipt,
    ParameterAccounting,
    TokenizerScaleAccounting,
    TokenizerScreenAccounting,
    TokenizerTargetDecisionContract,
    composition_receipt,
    estimate_dense_unique_parameters,
    lexical_parameter_share,
    parameter_accounting,
    tokenizer_screen_accounting,
)
from .bicameral import SwapLinear
from .bicameral_core import BicameralProjectedKeyValue, BicameralTransformerBlock
from .callosum import (
    CALLOSUM_RETENTION_TRIPWIRE,
    DeltaModePredictionReceipt,
    EmpiricalCarrierRetentionReceipt,
    HemisphereGradientCosineReceipt,
    PerBandBirkhoffCallosum,
    delta_mode_prediction_receipt,
    empirical_disagreement_retention_receipt,
    hemisphere_gradient_cosine_receipt,
)
from .config import (
    RATIFIED_TARGET_AUTHORITY,
    RATIFIED_TARGET_AUTHORITY_SHA256,
    RATIFIED_TARGET_D_MODEL,
    RATIFIED_TARGET_ROUNDED_UNIQUE_PARAMETERS_BY_CORE,
    RATIFIED_TARGET_REFERENCE_VOCAB_SIZE,
    REGISTERED_CORE_BLOCK_COUNTS,
    REGISTERED_PROXY_BLOCK_SPLITS,
    REGISTERED_TARGET_BLOCK_SPLITS,
    TOKENIZER_VOCAB_CANDIDATES,
    AblationLMConfig,
    registered_mu_r_configs,
    registered_proxy_reallocation_configs,
    registered_target_configs,
)
from .diagnostics import (
    RouterCalibrationDecision,
    RouterMomentSnapshot,
    router_calibration_stability,
)
from .geometry import Cl20Rotor, LaneModeState, cl20_rotate, lanes_to_modes
from .hadamard import orthonormal_wht, sequency_permutation, wht
from .model import AblationLM, AblationLMOutput
from .observatory import (
    ObservatoryBlocked,
    ObservatoryGuard,
    T14B_MEASUREMENT_ALGORITHM_SHA256,
    T14B_REGISTERED_K_VALUES,
    T14bGradientEvidence,
    T14bReceipt,
    measure_t14b_future_gradients,
)
from .observatory_events import (
    EVENT_KIND,
    INSTRUMENT_REGISTRY,
    InstrumentSpec,
    InstrumentTier,
    ObservatoryEvent,
    PrecisionRecord,
    emit_observatory_event,
)
from .rng import (
    ModuleRNGStream,
    construct_with_isolated_rng,
    derive_module_seed,
    isolated_module_rng,
)

__all__ = [
    "AblationLM",
    "AblationLMConfig",
    "AblationLMOutput",
    "BicameralProjectedKeyValue",
    "BicameralTransformerBlock",
    "CALLOSUM_RETENTION_TRIPWIRE",
    "Cl20Rotor",
    "CompositionReceipt",
    "DeltaModePredictionReceipt",
    "EmpiricalCarrierRetentionReceipt",
    "EVENT_KIND",
    "HemisphereGradientCosineReceipt",
    "INSTRUMENT_REGISTRY",
    "InstrumentSpec",
    "InstrumentTier",
    "LaneModeState",
    "ModuleRNGStream",
    "ObservatoryBlocked",
    "ObservatoryEvent",
    "ObservatoryGuard",
    "ParameterAccounting",
    "PerBandBirkhoffCallosum",
    "PrecisionRecord",
    "RATIFIED_TARGET_AUTHORITY",
    "RATIFIED_TARGET_AUTHORITY_SHA256",
    "RATIFIED_TARGET_D_MODEL",
    "RATIFIED_TARGET_ROUNDED_UNIQUE_PARAMETERS_BY_CORE",
    "RATIFIED_TARGET_REFERENCE_VOCAB_SIZE",
    "RouterCalibrationDecision",
    "RouterMomentSnapshot",
    "REGISTERED_CORE_BLOCK_COUNTS",
    "REGISTERED_PROXY_BLOCK_SPLITS",
    "REGISTERED_TARGET_BLOCK_SPLITS",
    "TOKENIZER_VOCAB_CANDIDATES",
    "SwapLinear",
    "T14B_MEASUREMENT_ALGORITHM_SHA256",
    "T14B_REGISTERED_K_VALUES",
    "T14bReceipt",
    "T14bGradientEvidence",
    "TokenizerScaleAccounting",
    "TokenizerScreenAccounting",
    "TokenizerTargetDecisionContract",
    "composition_receipt",
    "construct_with_isolated_rng",
    "derive_module_seed",
    "delta_mode_prediction_receipt",
    "estimate_dense_unique_parameters",
    "emit_observatory_event",
    "lexical_parameter_share",
    "measure_t14b_future_gradients",
    "orthonormal_wht",
    "cl20_rotate",
    "lanes_to_modes",
    "parameter_accounting",
    "empirical_disagreement_retention_receipt",
    "hemisphere_gradient_cosine_receipt",
    "isolated_module_rng",
    "registered_mu_r_configs",
    "registered_proxy_reallocation_configs",
    "registered_target_configs",
    "router_calibration_stability",
    "sequency_permutation",
    "tokenizer_screen_accounting",
    "wht",
]
